#!/bin/sh

if [ "$1" = "add" ]; then
    echo "apk called with: $*"
    exit 0
elif [ "$1" = "info" ]; then
    if [ -n "$APK_INFO_MOCK" ]; then
        echo "$*"
        exit 0
    fi
    exit 1
fi

exit 0
